# This is a basic workflow to help you get started with Actions

name: Lint

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master
      - release
  pull_request:
    branches:
      - master
      - release

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.1

      - name: Poetry setup
        uses: Gr1N/setup-poetry@v7

      - name: Check pyproject.toml
        run: poetry check

      - name: Install dependencies
        run: poetry install

      - name: Format
        run: black src && isort src

      - name: Lint
      - run: pflake8 src && isort --check-only --diff src # && mypy src
